### ISSUE TITLE
Add option for multiple parameters

### ISSUE THREAD

**Issue by VaronisDNMacClient** [circlecell/jsonlint.com#69]
Hi,

Any chance to add option for multiple parameters at once?

i.e, now I use the tool as

> jsonlint config1.json
> jsonlint config2.json
> jsonlint config3.json

What I would like to do is

> jsonlint config*.json

But that results in
```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'config*.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at main (C:\Users\XXX\AppData\Roaming\npm\node_modules\jsonlint\lib\cli.js:135:23)
    at Object.<anonymous> (C:\Users\XXX\AppData\Roaming\npm\node_modules\jsonlint\lib\cli.js:179:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by finom** [comment]
Sorry, that's not a CLI tool repository.
